 // This file has been generated by Specta. DO NOT EDIT.

export type Cursor = { type: "Default" } | { type: "Grabbing" } | { type: "Crosshair" } | { type: "Resize"; rotationDeg: number } | { type: "Rotate"; rotationDeg: number }

export type CursorChangeEvent = { cursor: Cursor }

export type DendronEvent = ({ type: "InteractionModeChange" } & InteractionModeChangeEvent) | ({ type: "InteractionToolChange" } & InteractionToolChangeEvent) | ({ type: "CursorChange" } & CursorChangeEvent)

export type InteractionMode = 
/**
 * Default canvas mode. Nothing is happening.
 */
{ type: "None" } | { type: "Inserting"; shape_variant: ShapeVariant }

export type InteractionModeChangeEvent = { interactionMode: InteractionMode }

export type InteractionModeLabel = "None" | "Inserting"

export type InteractionTool = 
/**
 * When the user wants to select nodes and move them around.
 */
{ type: "Select" } | 
/**
 * When the user wants to insert new shape nodes.
 */
{ type: "Shape"; variant: ShapeVariant }

export type InteractionToolChangeEvent = { interactionTool: InteractionTool }

export type ShapeVariant = "Rectangle" | "Ellipse" | "Star" | "Polygon"

export type SpectaExport = { events: DendronEvent }

export type Vec2 = [number, number]

export type XYWH = { position: Vec2; size: Vec2 }

