// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentificationLink } from "./IdentificationLink";
import type { Verification } from "./Verification";

export type EmailAddress = { id: string, emailAddress: string, verification: Verification | null, linkedTo: Array<IdentificationLink>, };
