// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrganizationMembership = { id: string, organizationId: string, role: string, createdAt: string, updatedAt: string, };
