// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verification } from "./Verification";

export type SamlAccount = { id: string, provider: string, emailAddress: string, firstName: string | null, lastName: string | null, verification: Verification | null, };
