// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmailAddress } from "./EmailAddress";
import type { ExternalAccount } from "./ExternalAccount";
import type { JsonValue } from "./serde_json/JsonValue";
import type { PhoneNumber } from "./PhoneNumber";
import type { SamlAccount } from "./SamlAccount";
import type { Web3Wallet } from "./Web3Wallet";

export type ClerkJsUser = { id: string, emailAddresses: Array<EmailAddress>, primaryEmailAddressId: string | null, primaryEmailAddress: EmailAddress | null, phoneNumbers: Array<PhoneNumber>, primaryPhoneNumberId: string | null, primaryPhoneNumber: PhoneNumber | null, username: string | null, firstName: string | null, lastName: string | null, fullName: string | null, imageUrl: string, hasImage: boolean, externalAccounts: Array<ExternalAccount>, verifiedExternalAccounts: Array<ExternalAccount>, web3Wallets: Array<Web3Wallet>, samlAccounts: Array<SamlAccount>, createdAt: number, updatedAt: number, lastSignInAt: number | null, lastActiveAt: number | null, legalAcceptedAt: number | null, publicMetadata: JsonValue, privateMetadata: JsonValue, unsafeMetadata: JsonValue, passwordEnabled: boolean, twoFactorEnabled: boolean, totpEnabled: boolean, backupCodeEnabled: boolean, banned: boolean, locked: boolean, hasVerifiedEmailAddress: boolean, hasVerifiedPhoneNumber: boolean, externalId: string | null, createOrganizationEnabled: boolean, createOrganizationsLimit: number | null, deleteSelfEnabled: boolean, };
