// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verification } from "./Verification";

export type PhoneNumber = { id: string, phoneNumber: string, verification: Verification | null, linkedTo: Array<string>, };
