// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verification } from "./Verification";

export type Web3Wallet = { id: string, web3Wallet: string, verification: Verification | null, };
