// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolState } from "./ToolState";

export type CrayonInEvent = { "type": "ChangeTool", "data": ToolState } | { "type": "ExitApp" };
